/// <reference path="integerVector.ts" />

interface StaticAttractor {
  position: IntegerVector;
  mass: number;
}

var X_POS_MAX = 2600;
var Y_POS_MAX = 1000;
var FIELD_RESOLUTION = 10;

var X_GRAVITY_MAX = X_POS_MAX / FIELD_RESOLUTION;
var Y_GRAVITY_MAX = Y_POS_MAX / FIELD_RESOLUTION;
var FIELD_ARRAY_SIZE = X_GRAVITY_MAX * Y_GRAVITY_MAX;
var GRAVITATIONAL_CONSTANT = 1000;

var EDGE_REPULSOR_STRENGTH = 1000;
var EDGE_REPULSOR_DIST = 10;

var pixel2fieldX = (x) => x;
var pixel2fieldY = (x) => x;

/**
 * Model the field of gravity generated by a set of StaticAttractores.
 * A gravity field is immutable. A new gravity field can be created by
 * adding an additional StaticAttractor
 */
class GravityField {
  private xField: Int16Array;
  private yField: Int16Array;
  constructor(xField: Int16Array, yField: Int16Array, attractor?: StaticAttractor) {
    this.xField = new Int16Array(FIELD_ARRAY_SIZE);
    this.yField = new Int16Array(FIELD_ARRAY_SIZE);

    var i = 0;
    for (var x=0; x<X_GRAVITY_MAX; x++) {
      for (var y=0; y<Y_GRAVITY_MAX; y++) {
        var g = attractor.mass * GRAVITATIONAL_CONSTANT / (Math.pow(x - attractor.position.x(), 2) + Math.pow(y - attractor.position.y(), 2));
        this.xField[i] = xField[i] + g;
        this.yField[i] = yField[i] + g;
      }
    }
  }

  public addAttractor(attractor: StaticAttractor): GravityField {
    return new GravityField(this.xField, this.yField, attractor);
  }
}

var initialField = function() {
  var xField = new Int16Array(FIELD_ARRAY_SIZE);
  var yField = new Int16Array(FIELD_ARRAY_SIZE);
  for (var x=0; x<EDGE_REPULSOR_DIST; x++) {
    var strength = EDGE_REPULSOR_STRENGTH * (EDGE_REPULSOR_DIST - x);
    for (var y=0; y<Y_GRAVITY_MAX; y++) {
      xField[x * X_GRAVITY_MAX + y] = strength;
      xField[(X_GRAVITY_MAX - x) * X_GRAVITY_MAX + y] = -strength;
    }
  }
  for (var y=0; y<EDGE_REPULSOR_DIST; y++) {
    var strength = EDGE_REPULSOR_STRENGTH * (EDGE_REPULSOR_DIST - y);
    for (var x=0; x<X_GRAVITY_MAX; x++) {
      yField[y * Y_GRAVITY_MAX + x] = strength;
      yField[(Y_GRAVITY_MAX - y) * Y_GRAVITY_MAX + x] = -strength;
    }
  }
  return new GravityField(xField, yField);
}();
